package intrinsics

import "strings"

func GoStdJSONWebHelperCode(target string) string {
	var b strings.Builder
	b.WriteString("func __std_json_escape(s string) string {\n")
	b.WriteString("\tenc, _ := json.Marshal(s)\n")
	b.WriteString("\tif len(enc) >= 2 {\n")
	b.WriteString("\t\treturn string(enc[1:len(enc)-1])\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn \"\"\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_validate(s string) bool {\n")
	b.WriteString("\treturn json.Valid([]byte(s))\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_pretty(s string) Result[string, Error] {\n")
	b.WriteString("\tvar v any\n")
	b.WriteString("\tif err := json.Unmarshal([]byte(s), &v); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tout, err := json.MarshalIndent(v, \"\", \"  \")\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(out), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_minify(s string) Result[string, Error] {\n")
	b.WriteString("\tif !json.Valid([]byte(s)) {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"invalid json\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar buf bytes.Buffer\n")
	b.WriteString("\tif err := json.Compact(&buf, []byte(s)); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: buf.String(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_value(s string, key string) (any, error) {\n")
	b.WriteString("\tdec := json.NewDecoder(strings.NewReader(s))\n")
	b.WriteString("\tdec.UseNumber()\n")
	b.WriteString("\ttok, err := dec.Token()\n")
	b.WriteString("\tif err != nil { return nil, err }\n")
	b.WriteString("\tif d, ok := tok.(json.Delim); !ok || d != '{' { return nil, fmt.Errorf(\"invalid json\") }\n")
	b.WriteString("\tfor dec.More() {\n")
	b.WriteString("\t\tk, err := dec.Token()\n")
	b.WriteString("\t\tif err != nil { return nil, err }\n")
	b.WriteString("\t\tks, ok := k.(string)\n")
	b.WriteString("\t\tif !ok { return nil, fmt.Errorf(\"invalid json\") }\n")
	b.WriteString("\t\tvar v any\n")
	b.WriteString("\t\tif err := dec.Decode(&v); err != nil { return nil, err }\n")
	b.WriteString("\t\tif ks == key { return v, nil }\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, fmt.Errorf(\"key not found\")\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_raw(s string, key string) Result[string, Error] {\n")
	b.WriteString("\tv, err := __std_json_get_value(s, key)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tout, err := json.Marshal(v)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(out), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_string(s string, key string) Result[string, Error] {\n")
	b.WriteString("\tv, err := __std_json_get_value(s, key)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tstr, ok := v.(string)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not a string\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: str, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_bool(s string, key string) Result[bool, Error] {\n")
	b.WriteString("\tv, err := __std_json_get_value(s, key)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tb, ok := v.(bool)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"not a bool\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: b, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_int(s string, key string) Result[int64, Error] {\n")
	b.WriteString("\tv, err := __std_json_get_value(s, key)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tswitch n := v.(type) {\n")
	b.WriteString("\tcase float64:\n")
	b.WriteString("\t\tif math.Trunc(n) != n { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not an int\"}} }\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: true, Value: int64(n), Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase json.Number:\n")
	b.WriteString("\t\tparsed, err := n.Int64()\n")
	b.WriteString("\t\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not an int\"}} }\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: true, Value: parsed, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase int64:\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: true, Value: n, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase int:\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: true, Value: int64(n), Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase string:\n")
	b.WriteString("\t\tparsed, err := strconv.ParseInt(strings.TrimSpace(n), 10, 64)\n")
	b.WriteString("\t\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not an int\"}} }\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: true, Value: parsed, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not an int\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_json_get_float(s string, key string) Result[float64, Error] {\n")
	b.WriteString("\tv, err := __std_json_get_value(s, key)\n")
	b.WriteString("\tif err != nil { return Result[float64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tswitch n := v.(type) {\n")
	b.WriteString("\tcase float64:\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: true, Value: n, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase json.Number:\n")
	b.WriteString("\t\tparsed, err := n.Float64()\n")
	b.WriteString("\t\tif err != nil { return Result[float64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not a float\"}} }\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: true, Value: parsed, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase int64:\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: true, Value: float64(n), Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase int:\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: true, Value: float64(n), Err: Error{Message: \"\"}}\n")
	b.WriteString("\tcase string:\n")
	b.WriteString("\t\tparsed, err := strconv.ParseFloat(strings.TrimSpace(n), 64)\n")
	b.WriteString("\t\tif err != nil { return Result[float64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not a float\"}} }\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: true, Value: parsed, Err: Error{Message: \"\"}}\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn Result[float64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"not a float\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	if target == "wasm" {
		b.WriteString("func __std_web_get_json(key string) Result[string, Error] {\n")
		b.WriteString("\tbridge := js.Global().Get(\"BAZIC_WEB\")\n")
		b.WriteString("\tif bridge.IsUndefined() || bridge.IsNull() {\n")
		b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"BAZIC_WEB not found\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\tres := bridge.Call(\"get\", key)\n")
		b.WriteString("\tif res.IsUndefined() || res.IsNull() {\n")
		b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"missing key\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: res.String(), Err: Error{Message: \"\"}}\n")
		b.WriteString("}\n")
		b.WriteString("func __std_web_set_json(key string, jsonText string) Result[bool, Error] {\n")
		b.WriteString("\tbridge := js.Global().Get(\"BAZIC_WEB\")\n")
		b.WriteString("\tif bridge.IsUndefined() || bridge.IsNull() {\n")
		b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"BAZIC_WEB not found\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\tbridge.Call(\"set\", key, jsonText)\n")
		b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
		b.WriteString("}\n\n")
	} else {
		b.WriteString("func __std_web_get_json(key string) Result[string, Error] {\n")
		b.WriteString("\t_ = key\n")
		b.WriteString("\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"web interop only supported in wasm\"}}\n")
		b.WriteString("}\n")
		b.WriteString("func __std_web_set_json(key string, jsonText string) Result[bool, Error] {\n")
		b.WriteString("\t_, _ = key, jsonText\n")
		b.WriteString("\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"web interop only supported in wasm\"}}\n")
		b.WriteString("}\n\n")
	}
	b.WriteString("func __std_base64_encode(s string) string {\n")
	b.WriteString("\treturn base64.StdEncoding.EncodeToString([]byte(s))\n")
	b.WriteString("}\n")
	b.WriteString("func __std_base64_decode(s string) Result[string, Error] {\n")
	b.WriteString("\tout, err := base64.StdEncoding.DecodeString(s)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(out), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	return b.String()
}
