package intrinsics

import "strings"

func GoStdDBHelperCode() string {
	var b strings.Builder
	b.WriteString("func __std_db_exec(path string, sqlText string) Result[bool, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\tif _, err := db.Exec(sqlText); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query(path string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar out strings.Builder\n")
	b.WriteString("\tout.WriteString(strings.Join(cols, \"\\t\"))\n")
	b.WriteString("\tout.WriteString(\"\\n\")\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString("\t\tif err := rows.Scan(ptrs...); err != nil {\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tfor i, v := range vals {\n")
	b.WriteString("\t\t\tif i > 0 { out.WriteString(\"\\t\") }\n")
	b.WriteString("\t\t\tswitch x := v.(type) {\n")
	b.WriteString("\t\t\tcase nil:\n")
	b.WriteString("\t\t\t\tout.WriteString(\"null\")\n")
	b.WriteString("\t\t\tcase []byte:\n")
	b.WriteString("\t\t\t\tout.WriteString(string(x))\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tout.WriteString(fmt.Sprint(x))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout.WriteString(\"\\n\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out.String(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func normalizeDBDriver(driver string) string {\n")
	b.WriteString("\tswitch driver {\n")
	b.WriteString("\tcase \"sqlite3\":\n")
	b.WriteString("\t\treturn \"sqlite\"\n")
	b.WriteString("\tcase \"postgresql\":\n")
	b.WriteString("\t\treturn \"postgres\"\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn driver\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	b.WriteString("func parseSQLParams(params string) ([]any, error) {\n")
	b.WriteString("\tif strings.TrimSpace(params) == \"\" { return nil, nil }\n")
	b.WriteString("\tlines := strings.Split(params, \"\\n\")\n")
	b.WriteString("\targs := make([]any, 0, len(lines))\n")
	b.WriteString("\tfor _, line := range lines {\n")
	b.WriteString("\t\tif line == \"\" { continue }\n")
	b.WriteString("\t\tparts := strings.SplitN(line, \":\", 2)\n")
	b.WriteString("\t\tif len(parts) != 2 { return nil, fmt.Errorf(\"invalid param\") }\n")
	b.WriteString("\t\tswitch parts[0] {\n")
	b.WriteString("\t\tcase \"str\":\n")
	b.WriteString("\t\t\targs = append(args, parts[1])\n")
	b.WriteString("\t\tcase \"int\":\n")
	b.WriteString("\t\t\tv, err := strconv.ParseInt(strings.TrimSpace(parts[1]), 10, 64)\n")
	b.WriteString("\t\t\tif err != nil { return nil, err }\n")
	b.WriteString("\t\t\targs = append(args, v)\n")
	b.WriteString("\t\tcase \"float\":\n")
	b.WriteString("\t\t\tv, err := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)\n")
	b.WriteString("\t\t\tif err != nil { return nil, err }\n")
	b.WriteString("\t\t\targs = append(args, v)\n")
	b.WriteString("\t\tcase \"bool\":\n")
	b.WriteString("\t\t\tval := strings.ToLower(strings.TrimSpace(parts[1]))\n")
	b.WriteString("\t\t\targs = append(args, val == \"true\" || val == \"1\")\n")
	b.WriteString("\t\tcase \"null\":\n")
	b.WriteString("\t\t\targs = append(args, nil)\n")
	b.WriteString("\t\tdefault:\n")
	b.WriteString("\t\t\treturn nil, fmt.Errorf(\"invalid param type\")\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn args, nil\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_with(driver string, dsn string, sqlText string) Result[bool, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"db_exec_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\tif _, err := db.Exec(sqlText); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_params(path string, sqlText string, params string) Result[bool, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tif _, err := db.Exec(sqlText, args...); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_params_with(driver string, dsn string, sqlText string, params string) Result[bool, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"db_exec_params_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tif _, err := db.Exec(sqlText, args...); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_with(driver string, dsn string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar out strings.Builder\n")
	b.WriteString("\tout.WriteString(strings.Join(cols, \"\\t\"))\n")
	b.WriteString("\tout.WriteString(\"\\n\")\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString("\t\tif err := rows.Scan(ptrs...); err != nil {\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tfor i, v := range vals {\n")
	b.WriteString("\t\t\tif i > 0 { out.WriteString(\"\\t\") }\n")
	b.WriteString("\t\t\tswitch x := v.(type) {\n")
	b.WriteString("\t\t\tcase nil:\n")
	b.WriteString("\t\t\t\tout.WriteString(\"null\")\n")
	b.WriteString("\t\t\tcase []byte:\n")
	b.WriteString("\t\t\t\tout.WriteString(string(x))\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tout.WriteString(fmt.Sprint(x))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout.WriteString(\"\\n\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out.String(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_params(path string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvar out strings.Builder\n")
	b.WriteString("\tout.WriteString(strings.Join(cols, \"\\t\"))\n")
	b.WriteString("\tout.WriteString(\"\\n\")\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString("\t\tif err := rows.Scan(ptrs...); err != nil {\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tfor i, v := range vals {\n")
	b.WriteString("\t\t\tif i > 0 { out.WriteString(\"\\t\") }\n")
	b.WriteString("\t\t\tswitch x := v.(type) {\n")
	b.WriteString("\t\t\tcase nil:\n")
	b.WriteString("\t\t\t\tout.WriteString(\"null\")\n")
	b.WriteString("\t\t\tcase []byte:\n")
	b.WriteString("\t\t\t\tout.WriteString(string(x))\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tout.WriteString(fmt.Sprint(x))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout.WriteString(\"\\n\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out.String(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_params_with(driver string, dsn string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_params_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvar out strings.Builder\n")
	b.WriteString("\tout.WriteString(strings.Join(cols, \"\\t\"))\n")
	b.WriteString("\tout.WriteString(\"\\n\")\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString("\t\tif err := rows.Scan(ptrs...); err != nil {\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tfor i, v := range vals {\n")
	b.WriteString("\t\t\tif i > 0 { out.WriteString(\"\\t\") }\n")
	b.WriteString("\t\t\tswitch x := v.(type) {\n")
	b.WriteString("\t\t\tcase nil:\n")
	b.WriteString("\t\t\t\tout.WriteString(\"null\")\n")
	b.WriteString("\t\t\tcase []byte:\n")
	b.WriteString("\t\t\t\tout.WriteString(string(x))\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tout.WriteString(fmt.Sprint(x))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tout.WriteString(\"\\n\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out.String(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_json_params(path string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tout, err := rowsToJSON(rows)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_json_params_with(driver string, dsn string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_json_params_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tout, err := rowsToJSON(rows)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_one_json_params(path string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tif !rows.Next() { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}} }\n")
	b.WriteString("\tif err := rows.Scan(ptrs...); err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdata, err := json.Marshal(rowToMap(cols, vals))\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_one_json_params_with(driver string, dsn string, sqlText string, params string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_one_json_params_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\trows, err := db.Query(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tif !rows.Next() { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}} }\n")
	b.WriteString("\tif err := rows.Scan(ptrs...); err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdata, err := json.Marshal(rowToMap(cols, vals))\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_returning_id_params(path string, sqlText string, params string) Result[int64, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tres, err := db.Exec(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tlast, err := res.LastInsertId()\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[int64, Error]{Is_ok: true, Value: last, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_returning_id_params_with(driver string, dsn string, sqlText string, params string) Result[int64, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"db_exec_returning_id_params_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\targs, err := parseSQLParams(params)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tres, err := db.Exec(sqlText, args...)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tlast, err := res.LastInsertId()\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[int64, Error]{Is_ok: true, Value: last, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func rowToMap(cols []string, vals []any) map[string]any {\n")
	b.WriteString("\tm := make(map[string]any, len(cols))\n")
	b.WriteString("\tfor i, col := range cols {\n")
	b.WriteString("\t\tv := vals[i]\n")
	b.WriteString("\t\tswitch x := v.(type) {\n")
	b.WriteString("\t\tcase nil:\n")
	b.WriteString("\t\t\tm[col] = nil\n")
	b.WriteString("\t\tcase []byte:\n")
	b.WriteString("\t\t\tm[col] = string(x)\n")
	b.WriteString("\t\tcase time.Time:\n")
	b.WriteString("\t\t\tm[col] = x.UTC().Format(time.RFC3339)\n")
	b.WriteString("\t\tdefault:\n")
	b.WriteString("\t\t\tm[col] = x\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn m\n")
	b.WriteString("}\n")
	b.WriteString("func rowsToJSON(rows *sql.Rows) (string, error) {\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return \"\", err }\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tvar buf bytes.Buffer\n")
	b.WriteString("\tbuf.WriteByte('[')\n")
	b.WriteString("\tfirst := true\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString("\t\tif err := rows.Scan(ptrs...); err != nil { return \"\", err }\n")
	b.WriteString("\t\tdata, err := json.Marshal(rowToMap(cols, vals))\n")
	b.WriteString("\t\tif err != nil { return \"\", err }\n")
	b.WriteString("\t\tif !first { buf.WriteByte(',') }\n")
	b.WriteString("\t\tfirst = false\n")
	b.WriteString("\t\t_, _ = buf.Write(data)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil { return \"\", err }\n")
	b.WriteString("\tbuf.WriteByte(']')\n")
	b.WriteString("\treturn buf.String(), nil\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_json(path string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tout, err := rowsToJSON(rows)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_json_with(driver string, dsn string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_json_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tout, err := rowsToJSON(rows)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_one_json(path string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tif !rows.Next() { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}} }\n")
	b.WriteString("\tif err := rows.Scan(ptrs...); err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdata, err := json.Marshal(rowToMap(cols, vals))\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_query_one_json_with(driver string, dsn string, sqlText string) Result[string, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"db_query_one_json_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\trows, err := db.Query(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer rows.Close()\n")
	b.WriteString("\tcols, err := rows.Columns()\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tvals := make([]any, len(cols))\n")
	b.WriteString("\tptrs := make([]any, len(cols))\n")
	b.WriteString("\tfor i := range vals { ptrs[i] = &vals[i] }\n")
	b.WriteString("\tif !rows.Next() { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}} }\n")
	b.WriteString("\tif err := rows.Scan(ptrs...); err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdata, err := json.Marshal(rowToMap(cols, vals))\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_returning_id(path string, sqlText string) Result[int64, Error] {\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\tres, err := db.Exec(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tlast, err := res.LastInsertId()\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[int64, Error]{Is_ok: true, Value: last, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_db_exec_returning_id_with(driver string, dsn string, sqlText string) Result[int64, Error] {\n")
	b.WriteString("\tif driver == \"\" { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: \"db_exec_returning_id_with: empty driver\"}} }\n")
	b.WriteString("\tdriver = normalizeDBDriver(driver)\n")
	b.WriteString("\tdb, err := sql.Open(driver, dsn)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\tres, err := db.Exec(sqlText)\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tlast, err := res.LastInsertId()\n")
	b.WriteString("\tif err != nil { return Result[int64, Error]{Is_ok: false, Value: 0, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[int64, Error]{Is_ok: true, Value: last, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	return b.String()
}
