package intrinsics

import "strings"

func GoStdCryptoSystemHelperCode(needsHmac bool, needsJwt bool, needsBcrypt bool) string {
	var b strings.Builder
	b.WriteString("func __std_open_url(url string) Result[bool, Error] {\n")
	b.WriteString("\tvar cmd *exec.Cmd\n")
	b.WriteString("\tif runtime.GOOS == \"windows\" {\n")
	b.WriteString("\t\tcmd = exec.Command(\"cmd\", \"/c\", \"start\", url)\n")
	b.WriteString("\t} else if runtime.GOOS == \"darwin\" {\n")
	b.WriteString("\t\tcmd = exec.Command(\"open\", url)\n")
	b.WriteString("\t} else {\n")
	b.WriteString("\t\tcmd = exec.Command(\"xdg-open\", url)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := cmd.Start(); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	b.WriteString("func __std_sha256_hex(s string) string {\n")
	b.WriteString("\tsum := sha256.Sum256([]byte(s))\n")
	b.WriteString("\treturn hex.EncodeToString(sum[:])\n")
	b.WriteString("}\n")
	if needsHmac {
		b.WriteString("func __std_hmac_sha256_hex(message string, secret string) string {\n")
		b.WriteString("\th := hmac.New(sha256.New, []byte(secret))\n")
		b.WriteString("\t_, _ = h.Write([]byte(message))\n")
		b.WriteString("\treturn hex.EncodeToString(h.Sum(nil))\n")
		b.WriteString("}\n")
	}
	if needsJwt {
		b.WriteString("func __std_jwt_sign_hs256(headerJSON string, payloadJSON string, secret string) Result[string, Error] {\n")
		b.WriteString("\tenc := base64.RawURLEncoding\n")
		b.WriteString("\theader := enc.EncodeToString([]byte(headerJSON))\n")
		b.WriteString("\tpayload := enc.EncodeToString([]byte(payloadJSON))\n")
		b.WriteString("\tsigning := header + \".\" + payload\n")
		b.WriteString("\th := hmac.New(sha256.New, []byte(secret))\n")
		b.WriteString("\t_, _ = h.Write([]byte(signing))\n")
		b.WriteString("\tsig := enc.EncodeToString(h.Sum(nil))\n")
		b.WriteString("\ttoken := signing + \".\" + sig\n")
		b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: token, Err: Error{Message: \"\"}}\n")
		b.WriteString("}\n")
		b.WriteString("func __std_jwt_verify_hs256(token string, secret string) Result[bool, Error] {\n")
		b.WriteString("\tparts := strings.Split(token, \".\")\n")
		b.WriteString("\tif len(parts) != 3 {\n")
		b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"invalid token\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\tsigning := parts[0] + \".\" + parts[1]\n")
		b.WriteString("\tsig := parts[2]\n")
		b.WriteString("\th := hmac.New(sha256.New, []byte(secret))\n")
		b.WriteString("\t_, _ = h.Write([]byte(signing))\n")
		b.WriteString("\texpected := base64.RawURLEncoding.EncodeToString(h.Sum(nil))\n")
		b.WriteString("\tif !hmac.Equal([]byte(sig), []byte(expected)) {\n")
		b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: false, Err: Error{Message: \"\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
		b.WriteString("}\n")
	}
	b.WriteString("func __std_random_hex(n int64) Result[string, Error] {\n")
	b.WriteString("\tif n <= 0 {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: true, Value: \"\", Err: Error{Message: \"\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tbuf := make([]byte, int(n))\n")
	b.WriteString("\tif _, err := rand.Read(buf); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: hex.EncodeToString(buf), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	if needsBcrypt {
		b.WriteString("func __std_bcrypt_hash(password string, cost int64) Result[string, Error] {\n")
		b.WriteString("\tif cost == 0 { cost = int64(bcrypt.DefaultCost) }\n")
		b.WriteString("\tif cost < int64(bcrypt.MinCost) { cost = int64(bcrypt.MinCost) }\n")
		b.WriteString("\tif cost > int64(bcrypt.MaxCost) { cost = int64(bcrypt.MaxCost) }\n")
		b.WriteString("\thash, err := bcrypt.GenerateFromPassword([]byte(password), int(cost))\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(hash), Err: Error{Message: \"\"}}\n")
		b.WriteString("}\n")
		b.WriteString("func __std_bcrypt_verify(password string, hash string) Result[bool, Error] {\n")
		b.WriteString("\terr := bcrypt.CompareHashAndPassword([]byte(hash), []byte(password))\n")
		b.WriteString("\tif err == nil {\n")
		b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\tif err == bcrypt.ErrMismatchedHashAndPassword {\n")
		b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: false, Err: Error{Message: \"\"}}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
		b.WriteString("}\n\n")
	}
	return b.String()
}
