package intrinsics

import "strings"

func GoStdSessionHelperCode() string {
	var b strings.Builder
	b.WriteString("func __std_session_init(path string) Result[bool, Error] {\n")
	b.WriteString("\tif path == \"\" {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"empty path\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif path == \"memory\" || path == \"memory:\" {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\t_, err = db.Exec(\"create table if not exists sessions (token_hash text primary key, user_id text not null, expires_at text)\")\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_session_put(path string, tokenHash string, userID string, expiresAt string) Result[bool, Error] {\n")
	b.WriteString("\tif path == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"empty path\"}} }\n")
	b.WriteString("\tif tokenHash == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"empty token\"}} }\n")
	b.WriteString("\tif path == \"memory\" || path == \"memory:\" {\n")
	b.WriteString("\t\tvar exp time.Time\n")
	b.WriteString("\t\tif strings.TrimSpace(expiresAt) != \"\" {\n")
	b.WriteString("\t\t\tt, err := time.Parse(time.RFC3339, strings.TrimSpace(expiresAt))\n")
	b.WriteString("\t\t\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\t\t\texp = t\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\t__bazic_session_mu.Lock()\n")
	b.WriteString("\t\t__bazic_session_store[tokenHash] = __bazic_session_entry{UserID: userID, ExpiresAt: exp}\n")
	b.WriteString("\t\t__bazic_session_mu.Unlock()\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\t_, err = db.Exec(\"insert into sessions (token_hash, user_id, expires_at) values (?, ?, ?) on conflict(token_hash) do update set user_id=excluded.user_id, expires_at=excluded.expires_at\", tokenHash, userID, expiresAt)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_session_get_user(path string, tokenHash string) Result[string, Error] {\n")
	b.WriteString("\tif path == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"empty path\"}} }\n")
	b.WriteString("\tif tokenHash == \"\" { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"empty token\"}} }\n")
	b.WriteString("\tif path == \"memory\" || path == \"memory:\" {\n")
	b.WriteString("\t\t__bazic_session_mu.Lock()\n")
	b.WriteString("\t\tentry, ok := __bazic_session_store[tokenHash]\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\t__bazic_session_mu.Unlock()\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif !entry.ExpiresAt.IsZero() && time.Now().After(entry.ExpiresAt) {\n")
	b.WriteString("\t\t\tdelete(__bazic_session_store, tokenHash)\n")
	b.WriteString("\t\t\t__bazic_session_mu.Unlock()\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"expired\"}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tuserID := entry.UserID\n")
	b.WriteString("\t\t__bazic_session_mu.Unlock()\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: true, Value: userID, Err: Error{Message: \"\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\tvar userID string\n")
	b.WriteString("\tvar expiresAt string\n")
	b.WriteString("\trow := db.QueryRow(\"select user_id, expires_at from sessions where token_hash = ?\", tokenHash)\n")
	b.WriteString("\tif err := row.Scan(&userID, &expiresAt); err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not found\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif strings.TrimSpace(expiresAt) != \"\" {\n")
	b.WriteString("\t\texp, err := time.Parse(time.RFC3339, strings.TrimSpace(expiresAt))\n")
	b.WriteString("\t\tif err == nil && time.Now().After(exp) {\n")
	b.WriteString("\t\t\t_, _ = db.Exec(\"delete from sessions where token_hash = ?\", tokenHash)\n")
	b.WriteString("\t\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"expired\"}}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: userID, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_session_delete(path string, tokenHash string) Result[bool, Error] {\n")
	b.WriteString("\tif path == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"empty path\"}} }\n")
	b.WriteString("\tif tokenHash == \"\" { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: \"empty token\"}} }\n")
	b.WriteString("\tif path == \"memory\" || path == \"memory:\" {\n")
	b.WriteString("\t\t__bazic_session_mu.Lock()\n")
	b.WriteString("\t\tdelete(__bazic_session_store, tokenHash)\n")
	b.WriteString("\t\t__bazic_session_mu.Unlock()\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdb, err := sql.Open(\"sqlite\", path)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\tdefer db.Close()\n")
	b.WriteString("\t_, err = db.Exec(\"delete from sessions where token_hash = ?\", tokenHash)\n")
	b.WriteString("\tif err != nil { return Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}} }\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	return b.String()
}
