package intrinsics

import "strings"

func GoStdRuntimeHelperCode() string {
	var b strings.Builder
	b.WriteString("func __std_read_file(path string) Result[string, Error] {\n")
	b.WriteString("\tdata, err := os.ReadFile(path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_write_file(path string, data string) Result[bool, Error] {\n")
	b.WriteString("\tif err := os.WriteFile(path, []byte(data), 0644); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_read_line() Result[string, Error] {\n")
	b.WriteString("\treader := bufio.NewReader(os.Stdin)\n")
	b.WriteString("\tline, err := reader.ReadString('\\n')\n")
	b.WriteString("\tif err != nil && err != io.EOF {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tline = strings.TrimRight(line, \"\\r\\n\")\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: line, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_read_all() Result[string, Error] {\n")
	b.WriteString("\tdata, err := io.ReadAll(os.Stdin)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_exists(path string) bool {\n")
	b.WriteString("\t_, err := os.Stat(path)\n")
	b.WriteString("\treturn err == nil\n")
	b.WriteString("}\n")
	b.WriteString("func __std_mkdir_all(path string) Result[bool, Error] {\n")
	b.WriteString("\tif err := os.MkdirAll(path, 0755); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_remove(path string) Result[bool, Error] {\n")
	b.WriteString("\tif err := os.RemoveAll(path); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_list_dir(path string) Result[string, Error] {\n")
	b.WriteString("\tentries, err := os.ReadDir(path)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tparts := make([]string, 0, len(entries))\n")
	b.WriteString("\tfor _, e := range entries {\n")
	b.WriteString("\t\tparts = append(parts, e.Name())\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: strings.Join(parts, \"\\n\"), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_unix_millis() int64 { return time.Now().UnixMilli() }\n")
	b.WriteString("func __std_sleep_ms(ms int64) { time.Sleep(time.Duration(ms) * time.Millisecond) }\n")
	b.WriteString("func __std_now_rfc3339() string { return time.Now().UTC().Format(time.RFC3339) }\n")
	b.WriteString("var __std_sb_mu sync.Mutex\n")
	b.WriteString("var __std_sb_seq uint64\n")
	b.WriteString("var __std_sb_map = map[string]*strings.Builder{}\n")
	b.WriteString("func __std_sb_lookup(handle string) *strings.Builder {\n")
	b.WriteString("\tif handle == \"\" {\n")
	b.WriteString("\t\t__std_sb_seq++\n")
	b.WriteString("\t\thandle = strconv.FormatUint(__std_sb_seq, 10)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tb, ok := __std_sb_map[handle]\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\tb = &strings.Builder{}\n")
	b.WriteString("\t\t__std_sb_map[handle] = b\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn b\n")
	b.WriteString("}\n")
	b.WriteString("func __std_sb_new() string {\n")
	b.WriteString("\t__std_sb_mu.Lock()\n")
	b.WriteString("\tdefer __std_sb_mu.Unlock()\n")
	b.WriteString("\t__std_sb_seq++\n")
	b.WriteString("\thandle := strconv.FormatUint(__std_sb_seq, 10)\n")
	b.WriteString("\t__std_sb_map[handle] = &strings.Builder{}\n")
	b.WriteString("\treturn handle\n")
	b.WriteString("}\n")
	b.WriteString("func __std_sb_append(handle string, s string) string {\n")
	b.WriteString("\t__std_sb_mu.Lock()\n")
	b.WriteString("\tdefer __std_sb_mu.Unlock()\n")
	b.WriteString("\tb := __std_sb_lookup(handle)\n")
	b.WriteString("\tb.WriteString(s)\n")
	b.WriteString("\tif handle == \"\" {\n")
	b.WriteString("\t\treturn strconv.FormatUint(__std_sb_seq, 10)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn handle\n")
	b.WriteString("}\n")
	b.WriteString("func __std_sb_string(handle string) string {\n")
	b.WriteString("\tif handle == \"\" { return \"\" }\n")
	b.WriteString("\t__std_sb_mu.Lock()\n")
	b.WriteString("\tdefer __std_sb_mu.Unlock()\n")
	b.WriteString("\tb, ok := __std_sb_map[handle]\n")
	b.WriteString("\tif !ok { return \"\" }\n")
	b.WriteString("\treturn b.String()\n")
	b.WriteString("}\n")
	b.WriteString("func __std_sb_len(handle string) int64 {\n")
	b.WriteString("\tif handle == \"\" { return 0 }\n")
	b.WriteString("\t__std_sb_mu.Lock()\n")
	b.WriteString("\tdefer __std_sb_mu.Unlock()\n")
	b.WriteString("\tb, ok := __std_sb_map[handle]\n")
	b.WriteString("\tif !ok { return 0 }\n")
	b.WriteString("\treturn int64(b.Len())\n")
	b.WriteString("}\n")
	b.WriteString("func __std_sb_clear(handle string) string {\n")
	b.WriteString("\tif handle == \"\" { return __std_sb_new() }\n")
	b.WriteString("\t__std_sb_mu.Lock()\n")
	b.WriteString("\tdefer __std_sb_mu.Unlock()\n")
	b.WriteString("\tb := __std_sb_lookup(handle)\n")
	b.WriteString("\tb.Reset()\n")
	b.WriteString("\treturn handle\n")
	b.WriteString("}\n")
	b.WriteString("func __std_time_add_days(rfc3339 string, days int64) Result[string, Error] {\n")
	b.WriteString("\tt, err := time.Parse(time.RFC3339, strings.TrimSpace(rfc3339))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tout := t.Add(time.Duration(days) * 24 * time.Hour).UTC().Format(time.RFC3339)\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: out, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_args() string {\n")
	b.WriteString("\tif len(os.Args) <= 1 { return \"\" }\n")
	b.WriteString("\treturn strings.Join(os.Args[1:], \"\\n\")\n")
	b.WriteString("}\n")
	b.WriteString("func __std_getenv(key string) Result[string, Error] {\n")
	b.WriteString("\tif key == \"\" {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"empty key\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tval, ok := os.LookupEnv(key)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: \"not set\"}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: val, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	b.WriteString("func __std_cwd() Result[string, Error] {\n")
	b.WriteString("\twd, err := os.Getwd()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: wd, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_chdir(path string) Result[bool, Error] {\n")
	b.WriteString("\tif err := os.Chdir(path); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_env_list() Result[string, Error] {\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: strings.Join(os.Environ(), \"\\n\"), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_temp_dir() Result[string, Error] {\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: os.TempDir(), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	b.WriteString("func __std_exe_path() Result[string, Error] {\n")
	b.WriteString("\tpath, err := os.Executable()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: path, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_home_dir() Result[string, Error] {\n")
	b.WriteString("\tpath, err := os.UserHomeDir()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: path, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n\n")
	b.WriteString("func __std_path_basename(path string) string { return filepath.Base(path) }\n")
	b.WriteString("func __std_path_dirname(path string) string { return filepath.Dir(path) }\n")
	b.WriteString("func __std_path_join(a string, b string) string { return filepath.Join(a, b) }\n\n")
	return b.String()
}
