package intrinsics

import (
	"fmt"
	"strings"
)

func GoStdHTTPHelperCode(httpResponseType string, hasHttpResponse bool, needsHeaderString bool) string {
	var b strings.Builder
	b.WriteString("func __std_http_get(url string) Result[string, Error] {\n")
	b.WriteString("\tresp, err := http.Get(url)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer resp.Body.Close()\n")
	b.WriteString("\tbody, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(body), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_http_post(url string, body string) Result[string, Error] {\n")
	b.WriteString("\tresp, err := http.Post(url, \"text/plain\", strings.NewReader(body))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer resp.Body.Close()\n")
	b.WriteString("\tdata, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_http_get_opts(url string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, tlsInsecure bool, caBundle string) Result[string, Error] {\n")
	b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treq, err := http.NewRequest(\"GET\", url, nil)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tapplyHeaders(req, headers, userAgent, \"\")\n")
	b.WriteString("\tresp, err := client.Do(req)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer resp.Body.Close()\n")
	b.WriteString("\tbody, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(body), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_http_post_opts(url string, body string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, contentType string, tlsInsecure bool, caBundle string) Result[string, Error] {\n")
	b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treq, err := http.NewRequest(\"POST\", url, strings.NewReader(body))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tapplyHeaders(req, headers, userAgent, contentType)\n")
	b.WriteString("\tresp, err := client.Do(req)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer resp.Body.Close()\n")
	b.WriteString("\tdata, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func __std_http_request(method string, url string, body string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, contentType string, tlsInsecure bool, caBundle string) Result[string, Error] {\n")
	b.WriteString("\tif method == \"\" { method = \"GET\" }\n")
	b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar reader io.Reader\n")
	b.WriteString("\tif body != \"\" { reader = strings.NewReader(body) }\n")
	b.WriteString("\treq, err := http.NewRequest(method, url, reader)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tapplyHeaders(req, headers, userAgent, contentType)\n")
	b.WriteString("\tresp, err := client.Do(req)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer resp.Body.Close()\n")
	b.WriteString("\tdata, err := io.ReadAll(resp.Body)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn Result[string, Error]{Is_ok: false, Value: \"\", Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[string, Error]{Is_ok: true, Value: string(data), Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	if hasHttpResponse {
		b.WriteString(fmt.Sprintf("func __std_http_get_opts_resp(url string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, tlsInsecure bool, caBundle string) Result[%s, Error] {\n", httpResponseType))
		b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\treq, err := http.NewRequest(\"GET\", url, nil)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tapplyHeaders(req, headers, userAgent, \"\")\n")
		b.WriteString("\tresp, err := client.Do(req)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tdefer resp.Body.Close()\n")
		b.WriteString("\tbody, err := io.ReadAll(resp.Body)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\treturn Result[%s, Error]{Is_ok: true, Value: %s{Status: int64(resp.StatusCode), Headers: headerString(resp.Header), Body: string(body)}, Err: Error{Message: \"\"}}\n", httpResponseType, httpResponseType))
		b.WriteString("}\n")
		b.WriteString(fmt.Sprintf("func __std_http_post_opts_resp(url string, body string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, contentType string, tlsInsecure bool, caBundle string) Result[%s, Error] {\n", httpResponseType))
		b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\treq, err := http.NewRequest(\"POST\", url, strings.NewReader(body))\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tapplyHeaders(req, headers, userAgent, contentType)\n")
		b.WriteString("\tresp, err := client.Do(req)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tdefer resp.Body.Close()\n")
		b.WriteString("\tdata, err := io.ReadAll(resp.Body)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\treturn Result[%s, Error]{Is_ok: true, Value: %s{Status: int64(resp.StatusCode), Headers: headerString(resp.Header), Body: string(data)}, Err: Error{Message: \"\"}}\n", httpResponseType, httpResponseType))
		b.WriteString("}\n")
		b.WriteString(fmt.Sprintf("func __std_http_request_resp(method string, url string, body string, connectTimeoutMs int64, timeoutMs int64, headers string, userAgent string, contentType string, tlsInsecure bool, caBundle string) Result[%s, Error] {\n", httpResponseType))
		b.WriteString("\tif method == \"\" { method = \"GET\" }\n")
		b.WriteString("\tclient, err := buildHTTPClient(connectTimeoutMs, timeoutMs, tlsInsecure, caBundle)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tvar reader io.Reader\n")
		b.WriteString("\tif body != \"\" { reader = strings.NewReader(body) }\n")
		b.WriteString("\treq, err := http.NewRequest(method, url, reader)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tapplyHeaders(req, headers, userAgent, contentType)\n")
		b.WriteString("\tresp, err := client.Do(req)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString("\tdefer resp.Body.Close()\n")
		b.WriteString("\tdata, err := io.ReadAll(resp.Body)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn Result[%s, Error]{Is_ok: false, Value: %s{}, Err: Error{Message: err.Error()}}\n", httpResponseType, httpResponseType))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\treturn Result[%s, Error]{Is_ok: true, Value: %s{Status: int64(resp.StatusCode), Headers: headerString(resp.Header), Body: string(data)}, Err: Error{Message: \"\"}}\n", httpResponseType, httpResponseType))
		b.WriteString("}\n")
	}
	b.WriteString("func __std_kv_get(kv string, key string) string {\n")
	b.WriteString("\tif key == \"\" || kv == \"\" { return \"\" }\n")
	b.WriteString("\tstart := 0\n")
	b.WriteString("\tfor start <= len(kv) {\n")
	b.WriteString("\t\tend := strings.IndexByte(kv[start:], '\\n')\n")
	b.WriteString("\t\tif end < 0 { end = len(kv) - start }\n")
	b.WriteString("\t\tline := kv[start : start+end]\n")
	b.WriteString("\t\tif line != \"\" {\n")
	b.WriteString("\t\t\tif idx := strings.IndexByte(line, '='); idx >= 0 {\n")
	b.WriteString("\t\t\t\tif line[:idx] == key { return line[idx+1:] }\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tstart += end + 1\n")
	b.WriteString("\t\tif start > len(kv) { break }\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn \"\"\n")
	b.WriteString("}\n")
	b.WriteString("func __std_header_get(headers string, key string) string {\n")
	b.WriteString("\tif key == \"\" || headers == \"\" { return \"\" }\n")
	b.WriteString("\tneedle := strings.TrimSpace(key)\n")
	b.WriteString("\tif needle == \"\" { return \"\" }\n")
	b.WriteString("\tstart := 0\n")
	b.WriteString("\tfor start <= len(headers) {\n")
	b.WriteString("\t\tend := strings.IndexByte(headers[start:], '\\n')\n")
	b.WriteString("\t\tif end < 0 { end = len(headers) - start }\n")
	b.WriteString("\t\tline := headers[start : start+end]\n")
	b.WriteString("\t\tif line != \"\" {\n")
	b.WriteString("\t\t\tif idx := strings.IndexByte(line, ':'); idx >= 0 {\n")
	b.WriteString("\t\t\t\tk := strings.TrimSpace(line[:idx])\n")
	b.WriteString("\t\t\t\tif strings.EqualFold(k, needle) { return strings.TrimSpace(line[idx+1:]) }\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tstart += end + 1\n")
	b.WriteString("\t\tif start > len(headers) { break }\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn \"\"\n")
	b.WriteString("}\n")
	b.WriteString("func __std_query_get(query string, key string) string {\n")
	b.WriteString("\tif key == \"\" { return \"\" }\n")
	b.WriteString("\tvals, err := url.ParseQuery(query)\n")
	b.WriteString("\tif err != nil { return \"\" }\n")
	b.WriteString("\treturn vals.Get(key)\n")
	b.WriteString("}\n")
	b.WriteString("func __std_http_serve_text(addr string, body string) Result[bool, Error] {\n")
	b.WriteString("\thandler := func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"text/plain; charset=utf-8\")\n")
	b.WriteString("\t\t_, _ = w.Write([]byte(body))\n")
	b.WriteString("\t}\n")
	b.WriteString("\thttp.HandleFunc(\"/\", handler)\n")
	b.WriteString("\tif err := http.ListenAndServe(addr, nil); err != nil {\n")
	b.WriteString("\t\treturn Result[bool, Error]{Is_ok: false, Value: false, Err: Error{Message: err.Error()}}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Result[bool, Error]{Is_ok: true, Value: true, Err: Error{Message: \"\"}}\n")
	b.WriteString("}\n")
	b.WriteString("func applyHeaders(req *http.Request, headers string, userAgent string, contentType string) {\n")
	b.WriteString("\tif userAgent != \"\" {\n")
	b.WriteString("\t\treq.Header.Set(\"User-Agent\", userAgent)\n")
	b.WriteString("\t} else if req.Header.Get(\"User-Agent\") == \"\" {\n")
	b.WriteString("\t\treq.Header.Set(\"User-Agent\", \"Bazic/1.0\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif contentType != \"\" {\n")
	b.WriteString("\t\treq.Header.Set(\"Content-Type\", contentType)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tlines := strings.Split(headers, \"\\n\")\n")
	b.WriteString("\tfor _, line := range lines {\n")
	b.WriteString("\t\tline = strings.TrimSpace(line)\n")
	b.WriteString("\t\tif line == \"\" { continue }\n")
	b.WriteString("\t\tparts := strings.SplitN(line, \":\", 2)\n")
	b.WriteString("\t\tif len(parts) != 2 { continue }\n")
	b.WriteString("\t\tkey := strings.TrimSpace(parts[0])\n")
	b.WriteString("\t\tval := strings.TrimSpace(parts[1])\n")
	b.WriteString("\t\tif key == \"\" { continue }\n")
	b.WriteString("\t\treq.Header.Set(key, val)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func buildHTTPClient(connectTimeoutMs int64, timeoutMs int64, tlsInsecure bool, caBundle string) (*http.Client, error) {\n")
	b.WriteString("\tclient := &http.Client{}\n")
	b.WriteString("\tif timeoutMs > 0 {\n")
	b.WriteString("\t\tclient.Timeout = time.Duration(timeoutMs) * time.Millisecond\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar tlsConfig *tls.Config\n")
	b.WriteString("\tif tlsInsecure {\n")
	b.WriteString("\t\ttlsConfig = &tls.Config{InsecureSkipVerify: true}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif caBundle != \"\" {\n")
	b.WriteString("\t\tpool := x509.NewCertPool()\n")
	b.WriteString("\t\tif !pool.AppendCertsFromPEM([]byte(caBundle)) {\n")
	b.WriteString("\t\t\treturn nil, fmt.Errorf(\"invalid CA bundle\")\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif tlsConfig == nil { tlsConfig = &tls.Config{} }\n")
	b.WriteString("\t\ttlsConfig.RootCAs = pool\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif connectTimeoutMs > 0 || tlsConfig != nil {\n")
	b.WriteString("\t\tdialer := &net.Dialer{}\n")
	b.WriteString("\t\tif connectTimeoutMs > 0 { dialer.Timeout = time.Duration(connectTimeoutMs) * time.Millisecond }\n")
	b.WriteString("\t\ttransport := &http.Transport{DialContext: dialer.DialContext}\n")
	b.WriteString("\t\tif tlsConfig != nil { transport.TLSClientConfig = tlsConfig }\n")
	b.WriteString("\t\tclient.Transport = transport\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn client, nil\n")
	b.WriteString("}\n\n")
	if needsHeaderString {
		b.WriteString("func headerString(h http.Header) string {\n")
		b.WriteString("\tvar b strings.Builder\n")
		b.WriteString("\tfor k, vals := range h {\n")
		b.WriteString("\t\tfor _, v := range vals {\n")
		b.WriteString("\t\t\tb.WriteString(k)\n")
		b.WriteString("\t\t\tb.WriteString(\": \")\n")
		b.WriteString("\t\t\tb.WriteString(v)\n")
		b.WriteString("\t\t\tb.WriteString(\"\\n\")\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn b.String()\n")
		b.WriteString("}\n\n")
	}
	return b.String()
}
